import json

notebook_content = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Demand Forecasting Model (Prophet + LSTM Ensemble)\n",
    "This notebook trains a demand forecasting model for each product to predict sales for the next 30 days.\n",
    "It uses Prophet as a baseline and an LSTM (PyTorch Lightning) if the Prophet MAPE is > 10%.\n",
    "Models are logged to MLflow."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Install required libraries (uncomment if running in a fresh environment)\n",
    "# !pip install pandas numpy prophet torch pytorch-lightning mlflow optuna scikit-learn"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "from prophet import Prophet\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "import pytorch_lightning as pl\n",
    "import mlflow\n",
    "import optuna\n",
    "from sklearn.preprocessing import MinMaxScaler\n",
    "from sklearn.metrics import mean_absolute_percentage_error\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "# Set random seed for reproducibility\n",
    "pl.seed_everything(42)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 1. Data Aggregation & Preprocessing\n",
    "# Path to the data file\n",
    "DATA_PATH = \"data/new_cleaned_retail_data_with_churn.csv\"\n",
    "\n",
    "def load_and_aggregate_data(filepath):\n",
    "    print(\"Loading data...\")\n",
    "    # Load dataset\n",
    "    df = pd.read_csv(filepath)\n",
    "    \n",
    "    # Ensure invoicedate is datetime\n",
    "    df['invoicedate'] = pd.to_datetime(df['invoicedate'])\n",
    "    \n",
    "    # Extract date from datetime\n",
    "    df['date'] = df['invoicedate'].dt.date\n",
    "    \n",
    "    print(\"Aggregating daily quantity per product...\")\n",
    "    # Aggregate quantity per stockcode per day\n",
    "    daily_sales = df.groupby(['date', 'stockcode'])['quantity'].sum().reset_index()\n",
    "    daily_sales['date'] = pd.to_datetime(daily_sales['date'])\n",
    "    \n",
    "    return daily_sales\n",
    "\n",
    "daily_sales = load_and_aggregate_data(DATA_PATH)\n",
    "daily_sales.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def prepare_product_data(df, product_id):\n",
    "    \"\"\"Fills missing dates with 0 and returns a continuous time series.\"\"\"\n",
    "    product_df = df[df['stockcode'] == product_id].copy()\n",
    "    if product_df.empty:\n",
    "        return product_df\n",
    "    \n",
    "    # Create a complete date range from min to max date\n",
    "    min_date, max_date = product_df['date'].min(), product_df['date'].max()\n",
    "    all_dates = pd.date_range(start=min_date, end=max_date, freq='D')\n",
    "    \n",
    "    # Set date as index and reindex\n",
    "    product_df = product_df.set_index('date')\n",
    "    product_df = product_df.reindex(all_dates, fill_value=0).reset_index()\n",
    "    product_df = product_df.rename(columns={'index': 'date'})\n",
    "    product_df['stockcode'] = product_id\n",
    "    \n",
    "    return product_df\n",
    "\n",
    "# Example: Get top 5 selling products to test\n",
    "top_products = daily_sales.groupby('stockcode')['quantity'].sum().sort_values(ascending=False).head(5).index.tolist()\n",
    "print(\"Top products to forecast:\", top_products)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 2. Prophet Baseline Model\n",
    "def train_prophet(product_df, test_days=30):\n",
    "    # Prophet requires columns 'ds' (date) and 'y' (target)\n",
    "    prophet_df = product_df[['date', 'quantity']].rename(columns={'date': 'ds', 'quantity': 'y'})\n",
    "    \n",
    "    # Split into train and validation (last 30 days)\n",
    "    if len(prophet_df) <= test_days:\n",
    "        raise ValueError(\"Not enough data to split into train and test\")\n",
    "        \n",
    "    train = prophet_df.iloc[:-test_days]\n",
    "    test = prophet_df.iloc[-test_days:]\n",
    "    \n",
    "    model = Prophet(yearly_seasonality=True, weekly_seasonality=True, daily_seasonality=False)\n",
    "    model.fit(train)\n",
    "    \n",
    "    future = model.make_future_dataframe(periods=test_days)\n",
    "    forecast = model.predict(future)\n",
    "    \n",
    "    # Calculate MAPE\n",
    "    y_true = test['y'].values\n",
    "    y_pred = forecast['yhat'].iloc[-test_days:].values\n",
    "    \n",
    "    # Handle zeros in denominator for MAPE\n",
    "    non_zero_idx = y_true != 0\n",
    "    if sum(non_zero_idx) == 0:\n",
    "        mape = 0.0\n",
    "    else:\n",
    "        mape = mean_absolute_percentage_error(y_true[non_zero_idx], y_pred[non_zero_idx])\n",
    "        \n",
    "    return model, forecast, mape, y_true, y_pred"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 3. LSTM Model (PyTorch Lightning)\n",
    "class TimeSeriesDataset(Dataset):\n",
    "    def __init__(self, data, seq_length=30):\n",
    "        self.data = data\n",
    "        self.seq_length = seq_length\n",
    "        \n",
    "    def __len__(self):\n",
    "        return len(self.data) - self.seq_length\n",
    "        \n",
    "    def __getitem__(self, idx):\n",
    "        x = self.data[idx:idx+self.seq_length]\n",
    "        y = self.data[idx+self.seq_length]\n",
    "        return torch.FloatTensor(x).unsqueeze(1), torch.FloatTensor([y])\n",
    "\n",
    "class LSTMForecaster(pl.LightningModule):\n",
    "    def __init__(self, input_dim=1, hidden_dim=64, num_layers=2, learning_rate=1e-3):\n",
    "        super().__init__()\n",
    "        self.save_hyperparameters()\n",
    "        self.lstm = nn.LSTM(input_dim, hidden_dim, num_layers, batch_first=True, dropout=0.2)\n",
    "        self.linear = nn.Linear(hidden_dim, 1)\n",
    "        self.criterion = nn.MSELoss()\n",
    "        \n",
    "    def forward(self, x):\n",
    "        lstm_out, _ = self.lstm(x)\n",
    "        out = self.linear(lstm_out[:, -1, :])\n",
    "        return out\n",
    "        \n",
    "    def training_step(self, batch, batch_idx):\n",
    "        x, y = batch\n",
    "        y_hat = self(x)\n",
    "        loss = self.criterion(y_hat, y)\n",
    "        self.log('train_loss', loss, prog_bar=True)\n",
    "        return loss\n",
    "        \n",
    "    def configure_optimizers(self):\n",
    "        return torch.optim.Adam(self.parameters(), lr=self.hparams.learning_rate)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def train_lstm(product_df, test_days=30, seq_length=30):\n",
    "    # Scale data\n",
    "    scaler = MinMaxScaler()\n",
    "    data_scaled = scaler.fit_transform(product_df[['quantity']].values)\n",
    "    \n",
    "    if len(data_scaled) <= test_days + seq_length:\n",
    "        raise ValueError(\"Not enough data for LSTM\")\n",
    "        \n",
    "    train_data = data_scaled[:-test_days]\n",
    "    test_data = data_scaled[-(test_days + seq_length):]\n",
    "    \n",
    "    train_dataset = TimeSeriesDataset(train_data, seq_length)\n",
    "    train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True, num_workers=0)\n",
    "    \n",
    "    model = LSTMForecaster()\n",
    "    \n",
    "    # Train using PyTorch Lightning (uses GPU if available in Colab)\n",
    "    trainer = pl.Trainer(max_epochs=50, accelerator='auto', devices='auto', enable_progress_bar=False, enable_model_summary=False)\n",
    "    trainer.fit(model, train_loader)\n",
    "    \n",
    "    # Predict\n",
    "    model.eval()\n",
    "    test_dataset = TimeSeriesDataset(test_data, seq_length)\n",
    "    test_loader = DataLoader(test_dataset, batch_size=1, shuffle=False)\n",
    "    \n",
    "    predictions = []\n",
    "    with torch.no_grad():\n",
    "        for x, _ in test_loader:\n",
    "            pred = model(x)\n",
    "            predictions.append(pred.item())\n",
    "            \n",
    "    # Inverse transform\n",
    "    predictions = scaler.inverse_transform(np.array(predictions).reshape(-1, 1)).flatten()\n",
    "    y_true = product_df['quantity'].iloc[-test_days:].values\n",
    "    \n",
    "    # Calculate MAPE\n",
    "    non_zero_idx = y_true != 0\n",
    "    if sum(non_zero_idx) == 0:\n",
    "        mape = 0.0\n",
    "    else:\n",
    "        mape = mean_absolute_percentage_error(y_true[non_zero_idx], predictions[non_zero_idx])\n",
    "        \n",
    "    return model, scaler, mape, y_true, predictions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 4. Ensemble and MLflow Logging\n",
    "mlflow.set_experiment(\"Demand_Forecasting\")\n",
    "\n",
    "def train_and_log_product(product_id):\n",
    "    print(f\"\\n--- Training for product {product_id} ---\")\n",
    "    product_df = prepare_product_data(daily_sales, product_id)\n",
    "    \n",
    "    if len(product_df) < 90:\n",
    "        print(f\"Skipping {product_id}: not enough data points ({len(product_df)} days).\")\n",
    "        return None\n",
    "        \n",
    "    with mlflow.start_run(run_name=f\"Product_{product_id}\"):\n",
    "        mlflow.log_param(\"product_id\", product_id)\n",
    "        \n",
    "        # 1. Train Prophet\n",
    "        try:\n",
    "            prophet_model, forecast, p_mape, y_true, p_pred = train_prophet(product_df)\n",
    "            mlflow.log_metric(\"prophet_mape\", p_mape)\n",
    "            print(f\"Prophet MAPE: {p_mape:.2%}\")\n",
    "        except Exception as e:\n",
    "            print(f\"Prophet failed: {e}\")\n",
    "            return None\n",
    "            \n",
    "        final_model_type = \"Prophet\"\n",
    "        final_mape = p_mape\n",
    "        final_pred = p_pred\n",
    "        \n",
    "        # 2. Check MAPE threshold, train LSTM if needed\n",
    "        lstm_model_info = None\n",
    "        if p_mape > 0.10:\n",
    "            print(\"Prophet MAPE > 10%. Training LSTM...\")\n",
    "            try:\n",
    "                lstm_model, scaler, l_mape, _, l_pred = train_lstm(product_df)\n",
    "                mlflow.log_metric(\"lstm_mape\", l_mape)\n",
    "                print(f\"LSTM MAPE: {l_mape:.2%}\")\n",
    "                \n",
    "                # Ensemble (Simple Average)\n",
    "                ens_pred = (p_pred + l_pred) / 2\n",
    "                non_zero_idx = y_true != 0\n",
    "                ens_mape = mean_absolute_percentage_error(y_true[non_zero_idx], ens_pred[non_zero_idx]) if sum(non_zero_idx) > 0 else 0\n",
    "                mlflow.log_metric(\"ensemble_mape\", ens_mape)\n",
    "                print(f\"Ensemble MAPE: {ens_mape:.2%}\")\n",
    "                \n",
    "                # Select best model for this product\n",
    "                best_mape = min(p_mape, l_mape, ens_mape)\n",
    "                if best_mape == ens_mape:\n",
    "                    final_model_type = \"Ensemble\"\n",
    "                    final_mape = ens_mape\n",
    "                    final_pred = ens_pred\n",
    "                elif best_mape == l_mape:\n",
    "                    final_model_type = \"LSTM\"\n",
    "                    final_mape = l_mape\n",
    "                    final_pred = l_pred\n",
    "                    \n",
    "                lstm_model_info = {'model': lstm_model, 'scaler': scaler}\n",
    "                \n",
    "            except Exception as e:\n",
    "                print(f\"LSTM failed: {e}\")\n",
    "        \n",
    "        mlflow.log_param(\"selected_model\", final_model_type)\n",
    "        mlflow.log_metric(\"final_mape\", final_mape)\n",
    "        print(f\"Selected Model: {final_model_type} with MAPE: {final_mape:.2%}\")\n",
    "        \n",
    "        # Save models to MLflow\n",
    "        # Note: Datasets might be large, in production you register to model registry\n",
    "        # mlflow.prophet.log_model(prophet_model, artifact_path=\"prophet_model\")\n",
    "        # if lstm_model_info:\n",
    "        #    mlflow.pytorch.log_model(lstm_model_info['model'], artifact_path=\"lstm_model\")\n",
    "        \n",
    "        return {\n",
    "            'product_id': product_id,\n",
    "            'model_type': final_model_type,\n",
    "            'mape': final_mape,\n",
    "            'prophet_model': prophet_model,\n",
    "            'lstm_info': lstm_model_info\n",
    "        }\n",
    "\n",
    "# Train for a few top products as a test\n",
    "results = {}\n",
    "for p in top_products[:2]: # Testing 2 products\n",
    "    res = train_and_log_product(p)\n",
    "    if res:\n",
    "        results[p] = res"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Function ready for Nandani (Backend) to review\n",
    "print(\"Training complete. The models are saved to MLflow.\")\n",
    "print(\"For inference, the backend will use a script similar to inference.py provided alongside this notebook.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open("demand_forecasting.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook_content, f, indent=1)
